/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qsa_talk_libstalk */

#ifndef _Included_com_qsatalk_cinjava
#define _Included_com_qsatalk_cinjava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qsa_talk_libstalk
 * Method:    start_talk
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL native_start_talk(JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_qsa_talk_libstalk
 * Method:    stop_talk
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL native_stop_talk(JNIEnv *, jobject);

#else
extern JNIEXPORT void JNICALL native_start_talk(JNIEnv *, jobject, jstring, jstring);
extern JNIEXPORT void JNICALL native_stop_talk(JNIEnv *, jobject);
#endif
#ifdef __cplusplus
}
#endif
